UseMySQL: false
MySQL:
  IP: localhost
  DB-Name: database-name
  Username: admin
  Password: superSecret
  Port: 3306
  Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8'
DetailedEnableMessage: false
DetailedDisableMessage: false
LockdownOnError: false
DefaultReason: "none"
TimeDiff: 0
MuteCommands:
- 'achat'
- 'ac'
- 'msg'
- 'w'
- 't'
- 'tell'
- 'gc'
ExemptPlayers:
DateFormat: "yyyy/MM/dd HH:mm"
EnableAllPermissionNodes: false
UUID-Fetcher:
  Dynamic: true
  Enabled: true
  Intern: false
  REST-API:
    URL: "https://api.mojang.com/users/profiles/minecraft/%NAME%?at=%TIMESTAMP%"
    Key: "id"
  BackUp-API:
    URL: "https://us.mc-api.net/v3/uuid/%NAME%"
    Key: "uuid"
WarnActions:
  3: "kick %PLAYER% &c&oYou have received your 3rd warning!"
TempPerms:
  1: 604800
  2: 2592000
  3: 31536000
Debug: false
Log Purge Days: 36500
Disable Prefix: true
Friendly Register Commands: false